apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: uwsgi-readiness-check
build:
  artifacts:
  - image: python
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
